{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret }}
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "%s:%s" "cloud-tsl-bot" (.Values.ghcrToken | default "REPLACE_ME") | b64enc) | b64enc }}
{{- end }}
