{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "demo-stack.name" . }}-frontend
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: frontend
  pollingInterval: 15
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: 1
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring:9090
        query: sum(rate(nginx_ingress_controller_requests{host="{{ include "demo-stack.host" . }}"}[2m]))
        threshold: "0.5"
{{- end }}
