apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      {{- include "demo-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "demo-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.images.minio.repository }}:{{ .Values.images.minio.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              value: demominio
            - name: MINIO_ROOT_PASSWORD
              value: demo-factory-minio-secret-key
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ (index .Values.tiers .Values.tier).minio.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    {{- include "demo-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
